serverKeystorePass: password
serverKeyPass: password
serverTruststorePass: password

clientKeystorePass: password
clientKeyPass: password
clientTruststorePass: password


authorizationCodeClientSecret: f6h1FTI8Q3-7UScPZDzfXA
clientCredentialsClientSecret: f6h1FTI8Q3-7UScPZDzfXA
refreshTokenClientSecret: f6h1FTI8Q3-7UScPZDzfXA

keyClientSecret: f6h1FTI8Q3-7UScPZDzfXA

emailPassword: change-to-real-password
